title: Logan Dixon
description: Athos the reptile king project
url: "https://logandixon-glitch.github.io"  # no trailing slash
baseurl: "/"                             # leading slash required

# Choose ONE of these (theme OR remote_theme):
# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown

# Helps the github-metadata plugin:
repository: estillcountyatc-computerscience/portfolio-template
